version: "2.0"
services:
  think-ruoyi-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    # volumes:
    #   - .:/app
    #   - ./dist:/etc/nginx/html
    #   - ./config/nginx:/etc/nginx/conf.d
    restart: always

