version: "2.0"
services:
  ruoyi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
    volumes:
    - ./logs:/logs
    container_name: ruoyi
    command: bash -c "java -Xms2048m -Xmx2048m -XX:PermSize=2048m -XX:MaxPermSize=2048m -XX:MaxNewSize=1024m -jar /ruoyi.jar"
    restart: always